ifeq ($(TARGET),)
ifeq ($(LIBRETRO),)
TARGET := retroarch.js
else
TARGET := $(LIBRETRO)_libretro.js
endif
endif

EOPT = USE_ZLIB=1 # Emscripten specific options
EOPTS = $(addprefix -s $(EMPTY), $(EOPT)) # Add '-s ' to each option

PTHREAD = 0
OS = Emscripten
OBJ :=
DEFINES := -DRARCH_INTERNAL -DHAVE_MAIN -s USE_PTHREADS=$(PTHREAD)
DEFINES += -DHAVE_FILTERS_BUILTIN

HAVE_DSP_FILTER = 1
HAVE_VIDEO_FILTER = 1
HAVE_OVERLAY = 0
HAVE_GLSL = 1
HAVE_SCREENSHOTS = 1
HAVE_REWIND = 1
HAVE_AUDIOMIXER = 1
HAVE_VIDEO_LAYOUT = 0
HAVE_CC_RESAMPLER = 1
HAVE_EGL    = 1
HAVE_OPENGLES = 1
HAVE_RJPEG  = 0
HAVE_RPNG   = 1
HAVE_EMSCRIPTEN = 1
HAVE_MENU = 1
HAVE_GFX_WIDGETS = 1
HAVE_RGUI = 1
HAVE_SDL = 0
HAVE_SDL2 = 0
HAVE_ZLIB = 1
HAVE_SHADERPIPELINE = 1
HAVE_STATIC_VIDEO_FILTERS = 1
HAVE_STATIC_AUDIO_FILTERS = 1
HAVE_STB_FONT = 1
HAVE_CONFIGFILE = 1
HAVE_CHEATS = 1
HAVE_IBXM = 1
HAVE_CORE_INFO_CACHE = 1

ASYNC ?= 0
ifeq ($(LIBRETRO), mupen64plus)
   ASYNC = 1
endif

# WRC (LTO = 1)
LTO ?= 1
ifeq ($(LIBRETRO), tyrquake)
   LTO = 0
endif

# WRC (MEM = 67108864)
MEMORY ?= 67108864
#MEMORY ?= 134217728

#ifeq ($(TARGET),parallel_n64_libretro.js)
#MEMORY = 201326592
#else
#MEMORY = 67108864
#endif

PRECISE_F32 = 1

OBJDIR := obj-emscripten2

#if you compile with SDL2 flag add this Emscripten flag "-s USE_SDL=2" to LDFLAGS:


#
# Non threaded..
#

LIBS    := -s USE_ZLIB=1
## WRC (CWrap and several exported methods)
#LDFLAGS := -L. --no-heap-copy -s $(LIBS) -s TOTAL_MEMORY=$(MEMORY) -s EXIT_RUNTIME=0 -s FULL_ES2=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['callMain', 'cwrap', 'ccall']" \
#           -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_free', '_cmd_savefiles', '_cmd_save_state', '_cmd_load_state', '_cmd_take_screenshot', '_cmd_audio_reinit', '_cmd_audio_stop', '_cmd_audio_start', '_cmd_pause', '_cmd_unpause', '_emscripten_mainloop', '_rwebaudio_enable', '_hash_generate_from_file', '_wrc_set_input', '_wrc_set_options', '_wrc_enable_bilinear_filter', '_wrc_start', '_wrc_step', '_wrc_save_state', '_wrc_load_state', '_wrc_update_mouse', '_wrc_on_key', '_wrc_force_aspect_ratio', '_wrc_set_shader', '_wrc_cheat_toggle', '_wrc_load_cheats_file', '_rcheevos_wrc_response']" \
#           --js-library emscripten/library_rwebaudio.js \
#           --js-library emscripten/library_rwebcam.js \
#           --js-library emscripten/library_errno_codes.js

#
# Threaded
#

CFLAGS += -pthread
CXXFLAGS += -pthread
LDFLAGS := -L. --no-heap-copy -s $(LIBS) -s TOTAL_MEMORY=$(MEMORY) -s EXIT_RUNTIME=0 -s FULL_ES2=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['callMain', 'cwrap', 'ccall']" \
           -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_FUNCTIONS="['_main', '_malloc',  '_free', '_cmd_savefiles', '_cmd_save_state', '_cmd_load_state', '_cmd_take_screenshot', '_cmd_audio_reinit', '_cmd_audio_stop', '_cmd_audio_start', '_cmd_pause', '_cmd_unpause', '_emscripten_mainloop', '_rwebaudio_enable', '_hash_generate_from_file', '_wrc_set_input', '_wrc_set_options', '_wrc_enable_bilinear_filter', '_wrc_start', '_wrc_step', '_wrc_save_state', '_wrc_load_state', '_wrc_update_mouse', '_wrc_on_key', '_wrc_force_aspect_ratio', '_wrc_set_shader', '_wrc_cheat_toggle', '_wrc_load_cheats_file', '_rcheevos_wrc_response']" \
           --js-library emscripten/library_rwebaudio.js \
           --js-library emscripten/library_rwebcam.js \
           --js-library emscripten/library_errno_codes.js \
	        -s WASM_MEM_MAX=1073741824 \
        -pthread -s PTHREAD_POOL_SIZE=8 #\
#        -s TOTAL_STACK=5242880 # added for YABAUSE.. should probably remove for other compiles

ifneq ($(PTHREAD), 0)
   LDFLAGS += -s USE_PTHREADS=$(PTHREAD) -s PTHREAD_POOL_SIZE=2
endif

#CFLAGS :=
#CXXFLAGS :=
#LDFLAGS := -L. --no-heap-copy -s $(LIBS) \
#           -s TOTAL_MEMORY=$(MEMORY) \
#           -s EXIT_RUNTIME=0 \
#           -s FULL_ES2=1 \
#           -s "EXTRA_EXPORTED_RUNTIME_METHODS=['callMain', 'cwrap']" \
#           -s ALLOW_MEMORY_GROWTH=1 \
#           -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_cmd_savefiles', '_cmd_save_state', '_cmd_load_state', '_cmd_take_screenshot', '_cmd_audio_reinit', '_cmd_audio_stop', '_cmd_audio_start', '_cmd_pause', '_cmd_unpause', '_emscripten_mainloop', '_rwebaudio_enable', '_hash_generate_from_file', '_wrc_set_input', '_wrc_set_options', '_wrc_enable_bilinear_filter', '_wrc_start', '_wrc_step', '_wrc_save_state', '_wrc_load_state', '_wrc_update_mouse', '_wrc_on_key', '_wrc_force_aspect_ratio', '_wrc_set_shader']" \
#           --js-library emscripten/library_rwebaudio.js \
#           --js-library emscripten/library_rwebcam.js \
#           --js-library emscripten/library_errno_codes.js \
#           -s WASM_MEM_MAX=1073741824 \
#           -s TOTAL_STACK=5242880 \
#           -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8

ifeq ($(ASYNC), 1)
   LDFLAGS += -s ASYNCIFY=$(ASYNC)
endif

ifeq ($(HAVE_SDL2), 1)
   LIBS += -s USE_SDL=2
   DEFINES += -DHAVE_SDL2
endif

include Makefile.common

# WRC (WRC define)
DEFINES += -DWRC -DWRC_INPUT

# WRC (Cheevos)
DEFINES += -DHAVE_CHEEVOS -DRC_DISABLE_LUA -DHAVE_CHD -DWANT_SUBCODE -DWANT_RAW_DATA_SECTOR
OBJ += cheevos/cheevos.o \
       cheevos/cheevos_client.o \
       cheevos/cheevos_menu.o \
       gfx/widgets/gfx_widget_achievement_popup_wrc.o \
       gfx/widgets/gfx_widget_leaderboard_display_wrc.o \
       libretro-common/formats/cdfs/cdfs.o \
       ../mame2003-plus-libretro/src/libretro-common/streams/chd_stream.o \
       deps/rcheevos/src/rcheevos/alloc.o \
       deps/rcheevos/src/rcheevos/compat.o \
       deps/rcheevos/src/rcheevos/condition.o \
       deps/rcheevos/src/rcheevos/condset.o \
       deps/rcheevos/src/rcheevos/consoleinfo.o \
       deps/rcheevos/src/rcheevos/format.o \
       deps/rcheevos/src/rcheevos/lboard.o \
       deps/rcheevos/src/rcheevos/memref.o \
       deps/rcheevos/src/rcheevos/operand.o \
       deps/rcheevos/src/rcheevos/rc_libretro.o \
       deps/rcheevos/src/rcheevos/richpresence.o \
       deps/rcheevos/src/rcheevos/runtime.o \
       deps/rcheevos/src/rcheevos/runtime_progress.o \
       deps/rcheevos/src/rcheevos/trigger.o \
       deps/rcheevos/src/rcheevos/value.o \
       deps/rcheevos/src/rhash/hash.o \
       deps/rcheevos/src/rapi/rc_api_common.o \
       deps/rcheevos/src/rapi/rc_api_runtime.o \
       deps/rcheevos/src/rapi/rc_api_user.o

# WRC (Cheevos include, no exceptions, no rtti)
CFLAGS += $(DEF_FLAGS) -Ideps -Ideps/stb -Ideps/rcheevos/include -fno-rtti -fno-exceptions
libretro = libretro_emscripten.bc

ifneq ($(V), 1)
   Q := @
endif

# -fsanitize=address

ifeq ($(DEBUG), 1)
   LDFLAGS += -O0 -g
   CFLAGS += -O0 -g
else
   LDFLAGS += -O3 -s WASM=1
   # WARNING: some optimizations can break some cores (ex: LTO breaks tyrquake)
   LDFLAGS += -s PRECISE_F32=$(PRECISE_F32)
   ifeq ($(LTO), 1)
      LDFLAGS += --llvm-lto 3
   endif
   CFLAGS += -O3
endif

CFLAGS += -Wall -I. -Ilibretro-common/include -std=gnu99 $(LIBS) \
          -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_cmd_savefiles', '_cmd_save_state', '_cmd_take_screenshot']"

RARCH_OBJ := $(addprefix $(OBJDIR)/,$(OBJ))

all: $(TARGET)

# Normal emscripten build (1.39.5)
$(TARGET): $(RARCH_OBJ) $(libretro)
	@$(if $(Q), $(shell echo echo LD $@),)
	$(Q)$(LD) -o $@ $(RARCH_OBJ) $(libretro) $(LIBS) $(LDFLAGS)

# Trying to get PPSSPP working, have to rename libretro_emscripten.bc file to libreatro_emscripten.a
#$(TARGET): $(RARCH_OBJ)
#	$(Q)emcc -o $@ $(RARCH_OBJ) -L. -lretro_emscripten -L. -lretro_ppsspp_emscripten $(LIBS) $(LDFLAGS) -s LINKABLE=1


#$(TARGET): $(RARCH_OBJ) $(libretro)
#	@$(if $(Q), $(shell echo echo LD $@),)
#	$(info --- Linking command ---)
#	$(info emcc -o $@ $(RARCH_OBJ) $(libretro) $(LIBS) $(LDFLAGS))
#	$(Q)emcc -o $@ $(RARCH_OBJ) $(libretro) $(LIBS) $(LDFLAGS)

$(OBJDIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo CC $<),)
	$(Q)$(CC) $(CFLAGS) $(DEFINES) $(EOPTS) -c -o $@ $<

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo CXX $<),)
	$(Q)$(CXX) $(CXXFLAGS) $(DEFINES) $(EOPTS) -c -o $@ $<

clean:
	rm -rf $(OBJDIR)
	rm -f $(TARGET)

.PHONY: all clean

